name: CANFAR Storage Prototype
permalink: /news/:year/:month/:day/:title/
relative_permalinks: false
markdown: kramdown
future: true
github:
  repository_url: 'https://github.com/canfar/storage-prototype'
